from rest_framework import serializers
from .models import Gk

class GkSerializer(serializers.ModelSerializer):
    """Serializer for Gk model"""

    class Meta:
        model = Gk
        fields = (
            'sofifa_id',
            'player_url',
            'short_name',
            'long_name',
            'age',
            'dob',
            'height_cm',
            'weight_kg',
            'nationality',
            'club',
            'overall',
            'potential',
            'value_eur',
            'wage_eur',
            'player_positions',
            'preferred_foot',
            'international_reputation',
            'weak_foot',
            'skill_moves',
            'work_rate',
            'body_type',
            'gk_diving',
            'gk_handling',
            'gk_kicking',
            'gk_reflexes',
            'gk_speed',
            'gk_positioning',
            'player_traits',
            'attacking_crossing',
            'attacking_finishing',
            'attacking_heading_accuracy',
            'attacking_short_passing',
            'attacking_volleys',
            'skill_dribbling',
            'skill_curve',
            'skill_fk_accuracy',
            'skill_long_passing',
            'skill_ball_control',
            'movement_acceleration',
            'movement_sprint_speed',
            'movement_agility',
            'movement_reactions',
            'movement_balance',
            'power_shot_power',
            'power_jumping',
            'power_stamina',
            'power_strength',
            'power_long_shots',
            'mentality_aggression',
            'mentality_interceptions',
            'mentality_positioning',
            'mentality_vision',
            'mentality_penalties',
            'mentality_composure',
            'defending_marking',
            'defending_standing_tackle',
            'defending_sliding_tackle',
            'goalkeeping_diving',
            'goalkeeping_handling',
            'goalkeeping_kicking',
            'goalkeeping_positioning',
            'goalkeeping_reflexes',
            'player_image'
        )